repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ["--maxkb=50000"]
        exclude: '\.h5$'
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--no-sort-keys"]
      - id: check-yaml
        args: ["--allow-multiple-documents"]
        exclude: ".github"
      - id: check-case-conflict
      - id: check-xml
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: debug-statements
  - repo: https://github.com/crate-ci/typos
    rev: v1.36.3
    hooks:
      - id: typos
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.13.2
    hooks:
      - id: ruff-format
        args: [--verbose]
        types_or: [python, pyi]
      - id: ruff-check
        args: [--fix, --config=pyproject.toml]
        types_or: [python, pyi]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.18.2"
    hooks:
      - id: mypy
        types: [python]
        args: [--config-file=pyproject.toml, -p, r2x_reeds]
        pass_filenames: false
        language: system
        entry: uv run mypy
